#This file will active when  'dev' profile active
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: sam
    platform: mysql #bunu belirtmemiz initialize sql'ini bu platform ismine gore almsasini sagliyacak(data-mysql.sql gibi)
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: sam_database_create.sql